### ISSUE TITLE
Colours for Keyboard bindings and counsel-mx like behaviour?

### ISSUE THREAD

**Issue by technician77** [DarwinAwardWinner/smex#21]
First, keyboard bindings seem to have no colour on my system. Is there something I need to customize to get them in a different colour?

Then counsel-mx starts out with only showing the candidates that beginn with the typed expression. When removing the ^ sign it searches for candidates that have the typed expression anywhere. Amx starts with the latter one, so is there a way to get the ^ behaviour?

Finally, iirc counsel-mx utilizes smex for history. If smex is not actively developed anymore wouldn't it make sense for counsel-mx to switch over to amx?

This is counsel-mx:
![image](https://user-images.githubusercontent.com/18722291/29306046-e8721926-819b-11e7-811a-05b16c3847b2.png)
This is amx:
![image](https://user-images.githubusercontent.com/18722291/29306130-4826a120-819c-11e7-8ee8-df4349156346.png)

**Comment by DarwinAwardWinner** [comment]
The point of amx is to work with any completion system, so it is generic and generally doesn't leverage the specific features of any one completion system. So there's no way to add color to key bindings in amx. Since amx is based on smex, which uses exclusively ido for completion, amx most likely works best with ido completion, although I've made some effort to test it with other completion systems. In all likelihood, counsel is probably the better way to get ivy completion for M-x.

As for sharing history between amx and counsel/smex, amx is designed not to interfere with smex, so it uses separate variables even though the history format is identical. I suppose I could add an optional mode to force it to share history with smex. Or counsel could be modified to calling the equivalent amx functions if amx is loaded, and call the smex functions otherwise. But I have nothing to do with the development of counsel.

**Comment by technician77** [comment]
Thanks for the insight, so I'll switch back to counsel-mx. I might ask Oleh if he could support amx additionally to smex. But if I do so I should be able to point out all the advantages. Since he seemingly only uses smex for history purposes is there anything more than that from which counsel-mx would benefit except using an activly maintained package? Would there be even disadvantages?

**Comment by DarwinAwardWinner** [comment]
If you're just using the history mechanism of amx and nothing else, it would be identical to smex.

**Comment by DarwinAwardWinner** [comment]
Oh, I realized that I hadn't addressed one of your questions, which was about amx not requiring the command to start with the user's entry. I guess counsel defaults to using regular expressions, while amx uses `ivy-completing-read`, which I guess does not default to regular expressions. There's probably an option in ivy to change that.
